Vagrant.configure("2") do |config|

  #config.vm.provision "shell", path: "script.sh"
  config.vm.define "server" do |server|
    server.vm.box = "spox/ubuntu-arm"
    server.vm.network "private_network", ip: "172.17.177.21"
    server.vm.hostname = "server"
    server.vm.provision "shell", path: "script.sh"
  end

  config.vm.define "client" do |client|
    client.vm.box = "spox/ubuntu-arm"
    client.vm.network "private_network", ip: "172.17.177.22"
    client.vm.hostname = "client"
    client.vm.provision "shell", path: "client.sh"
  end
end

