apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
data:
  WORDPRESS_DB_HOST: {{ .Values.mysql.service.name }}:{{ .Values.mysql.service.port }}
  WORDPRESS_DB_NAME: {{ .Values.mysql.database }}
  WORDPRESS_DB_USER: {{ .Values.mysql.user }}