apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.service.name }}
  labels:
    app: {{ .Values.mysql.service.name }}
spec:
  ports:
    - port: {{ .Values.mysql.service.port }}
      targetPort: 3306
  selector:
    app: {{ .Values.mysql.service.name }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.mysql.service.name }}
spec:
  serviceName: {{ .Values.mysql.service.name }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.mysql.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mysql.service.name }}
    spec:
      containers:
      - name: mysql
        image: {{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secrets
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_DATABASE
            value: {{ .Values.mysql.database }}
          - name: MYSQL_USER
            value: {{ .Values.mysql.user }}
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secrets
                key: MYSQL_PASSWORD
        ports:
          - containerPort: 3306
        volumeMounts:
          - name: mysql-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: {{ .Values.mysql.service.name }}-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mysql.service.name }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.mysql.size }}
  storageClassName: {{ .Values.persistence.mysql.storageClass }}
