apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword | b64enc | quote }}
  MYSQL_PASSWORD: {{ .Values.mysql.password | b64enc | quote }}
  WORDPRESS_DB_PASSWORD: {{ .Values.mysql.password | b64enc | quote }}