# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.define "prod" do |prod|
    prod.vm.box = "spox/ubuntu-arm"
    prod.vm.box_version = "1.0.0"
    prod.vm.box_check_update = false
    prod.vm.hostname = "prod"
    prod.vm.define "prod"
    prod.vm.network "private_network", ip: "172.17.177.22"
  end

  config.vm.define "dev" do |dev|
    dev.vm.box = "spox/ubuntu-arm"
    dev.vm.box_version = "1.0.0"
    dev.vm.box_check_update = false
    dev.vm.hostname = "dev"
    dev.vm.define "dev"
    dev.vm.network "private_network", ip: "172.17.177.21"
  end

end