pipeline {
    agent {
        dockerContainer('maven:3.9.2')
    }
    environment {
        GITHUB_CRED = "git branch: 'lesson26', changelog: false, credentialsId: 'github', poll: false, url: 'https://github.com/JiceO-o/codeby-devops.git'"
        GITHUB_URL = "https://github.com/JiceO-o/codeby-devops.git"
        }
    stages {
        stage('Build') {
            parallel {
                stage('hello-world!') {
                    when {
                        changeset "**/hello-world!/**"
                    }
                    steps {
                        dir('lesson26/hello-world!'){
                            sh 'mvn -B -DskipTests clean package'
                            sh 'ls -la'
                            sh 'ls -la target'
                        }
                    }
                }
                stage('Hello Jenkins') {
                    when {
                        changeset "**/hello-jenkins!/**"
                    }
                    steps {
                        dir('lesson26/hello-jenkins!'){
                            sh 'mvn -B -DskipTests clean package'
                            sh 'ls -la'
                            sh 'ls -la target'
                        }
                    }
                }
                stage('hello-devops!') {
                    when {
                        changeset "**/hello-devops!/**"
                    }
                    steps {
                        dir('lesson26/hello-devops!'){
                            sh 'mvn -B -DskipTests clean package'
                            sh 'ls -la'
                            sh 'ls -la target'
                        }
                    }
                }
            }
        stage('Test') {
            parallel {
                stage('Hello World') {
                    when {
                        changeset "**/hello-world!/**"
                    }
                    steps {
                        dir('lesson26/hello-world!'){
                            sh 'mvn test'
                        }
                    }
                }
                stage('Hello Jenkins') {
                    when {
                        changeset "**/hello-jenkins!/**"
                    }
                    steps {
                        dir('lesson26/hello-jenkins!'){
                            sh 'mvn test'
                        }
                    }
                }
                stage('hello-devops!') {
                    when {
                        changeset "**/hello-devops!/**"
                    }
                    steps {
                        dir('lesson26/hello-devops!'){
                            sh 'mvn test'
                        }
                    }
                }
            }
        }
        stage('Deliver') {
            parallel {
                stage('Hello World') {
                    when {
                        changeset "**/hello-world!/**"
                    }
                    steps {
                        sh "./lesson26/hello-world!/jenkins/scripts/deliver.sh"
                    }
                }
                stage('Hello Jenkins') {
                    when {
                        changeset "**/hello-jenkins!/**"
                    }
                    steps {
                        sh "./lesson26/hello-jenkins!/jenkins/scripts/deliver.sh"
                    }
                }
                stage('hello-devops!') {
                    when {
                        changeset "**/hello-devops!/**"
                    }
                    steps {
                        sh "./lesson26/hello-devops!/jenkins/scripts/deliver.sh"
                    }
                }
            }
        }
    }
}
