kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: false
nodes:
  - role: control-plane
  - role: worker
    labels:
      node-type: wordpress-node
  - role: worker
    labels:
      node-type: mysql-node
