Vagrant.configure("2") do |config|

  config.vm.define "server" do |server|
    server.vm.box = "spox/ubuntu-arm"
    server.vm.network "private_network", ip: "172.17.177.21"
    server.vm.hostname = "server"
    #server.vm.provision "shell", path: "script.sh"
  end

  config.vm.define "store" do |store|
    store.vm.box = "spox/ubuntu-arm"
    store.vm.network "private_network", ip: "172.17.177.22"
    store.vm.hostname = "store"
  end
end